---
- hosts: all
  become: true
  roles:
     - role: system/essential
       tags:
          - essential
          - system
     - role: system/docker
       tags:
          - docker
          - system